softeerbootcamp4th/Team5-WatermelonClap-BE

README.md

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-25
리드미 수정

docs: readme jira 예시 수정, 선착순 설계 그림 제거

---

src/main/java/com/watermelon/server/admin/controller/AdminLotteryController.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseAdminLotteryWinnerDto.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseAdminPartsWinnerDto.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseLotteryApplierDto.java
src/main/java/com/watermelon/server/randomevent/controller/LotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/AdminCheckStatus.java
src/main/java/com/watermelon/server/randomevent/domain/Link.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryReward.java
src/main/java/com/watermelon/server/randomevent/dto/response/ResponseRewardInfoDto.java
src/main/java/com/watermelon/server/randomevent/parts/domain/PartsReward.java
src/main/java/com/watermelon/server/randomevent/parts/repository/PartsRewardRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryApplierRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryRewardRepository.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/controller/LotteryControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-129

WB-129-api-server

---

src/main/java/com/watermelon/server/randomevent/controller/LotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryReward.java
src/main/java/com/watermelon/server/randomevent/dto/response/ResponseRewardInfoDto.java
src/main/java/com/watermelon/server/randomevent/parts/domain/PartsReward.java
src/main/java/com/watermelon/server/randomevent/parts/repository/PartsRewardRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryRewardRepository.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/randomevent/controller/LotteryControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-78

WB-78-api-server

---

src/main/java/com/watermelon/server/admin/controller/AdminLotteryController.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseLotteryApplierDto.java
src/main/java/com/watermelon/server/randomevent/controller/LotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/Link.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryReward.java
src/main/java/com/watermelon/server/randomevent/dto/response/ResponseRewardInfoDto.java
src/main/java/com/watermelon/server/randomevent/parts/domain/PartsReward.java
src/main/java/com/watermelon/server/randomevent/parts/repository/PartsRewardRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryApplierRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryRewardRepository.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/controller/LotteryControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-128

WB-128-api-server

---

src/main/java/com/watermelon/server/admin/controller/AdminLotteryController.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseAdminLotteryWinnerDto.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseLotteryApplierDto.java
src/main/java/com/watermelon/server/randomevent/controller/LotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/AdminCheckStatus.java
src/main/java/com/watermelon/server/randomevent/domain/Link.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryReward.java
src/main/java/com/watermelon/server/randomevent/dto/response/ResponseRewardInfoDto.java
src/main/java/com/watermelon/server/randomevent/parts/domain/PartsReward.java
src/main/java/com/watermelon/server/randomevent/parts/repository/PartsRewardRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryApplierRepository.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryRewardRepository.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/controller/LotteryControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-130

WB-130-api-server

---

src/main/java/com/watermelon/server/admin/controller/AdminLotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/parts/controller/PartsControllerTest.java

https://watermelon-clap.atlassian.net/browse/WB-131?atlOrigin=eyJpIjoiODIyNTQwOTYxYjBkNDFlM2EzMGY5NzJkNmZlMzhlMTMiLCJwIjoiaiJ9

WB-131-api-server

---

src/main/java/com/watermelon/server/admin/controller/AdminLotteryController.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/parts/controller/PartsControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-133

WB-133-api-server

---

.github/workflows/pr-test.yml
build.gradle
src/main/java/com/watermelon/server/event/order/result/service/OrderResultQueryService.java
src/main/java/com/watermelon/server/redis/config/EmbeddedRedisConfig.java
src/main/java/com/watermelon/server/redis/config/RedissonConfig.java
src/main/resources/application.yml
src/test/java/com/watermelon/server/event/order/result/repository/OrderResultRepositoryTest.java
src/test/java/com/watermelon/server/event/order/result/service/OrderResultLockTest.java
src/test/java/com/watermelon/server/event/order/result/service/OrderResultQueryServiceTest.java

Wb- 137 api server embedded redis

---

src/main/java/com/watermelon/server/admin/controller/AdminExpectationController.java
src/main/java/com/watermelon/server/admin/controller/AdminOrderEventController.java
src/main/java/com/watermelon/server/admin/dto/response/ResponseAdminExpectationApprovedDto.java
src/main/java/com/watermelon/server/admin/service/AdminOrderEventService.java
src/main/java/com/watermelon/server/randomevent/controller/ExpectationController.java
src/main/java/com/watermelon/server/randomevent/domain/Expectation.java
src/main/java/com/watermelon/server/randomevent/dto/response/ResponseExpectationDto.java
src/main/java/com/watermelon/server/randomevent/error/ExpectationNotExist.java
src/main/java/com/watermelon/server/randomevent/repository/ExpectationRepository.java
src/main/java/com/watermelon/server/randomevent/service/ExpectationService.java
src/test/java/com/watermelon/server/admin/controller/AdminOrderEventControllerTest.java
src/test/java/com/watermelon/server/admin/service/AdminOrderEventServiceTest.java
src/test/java/com/watermelon/server/randomevent/repository/ExpectationRepositoryTest.java
src/test/java/com/watermelon/server/randomevent/service/ExpectationServiceTest.java

Wb 93 api server

---

src/main/java/com/watermelon/server/admin/dto/response/ResponseLotteryApplierDto.java
src/main/java/com/watermelon/server/common/config/WebConfig.java
src/main/java/com/watermelon/server/common/constants/HttpConstants.java
src/main/java/com/watermelon/server/common/constants/PathConstants.java
src/main/java/com/watermelon/server/randomevent/auth/interceptor/LoginCheckInterceptor.java
src/main/java/com/watermelon/server/randomevent/domain/Link.java
src/main/java/com/watermelon/server/randomevent/domain/LotteryApplier.java
src/main/java/com/watermelon/server/randomevent/link/controller/LinkController.java
src/main/java/com/watermelon/server/randomevent/link/dto/MyLinkDto.java
src/main/java/com/watermelon/server/randomevent/link/exception/LinkNotFoundException.java
src/main/java/com/watermelon/server/randomevent/link/repository/LinkRepository.java
src/main/java/com/watermelon/server/randomevent/link/service/LinkService.java
src/main/java/com/watermelon/server/randomevent/link/service/LinkServiceImpl.java
src/main/java/com/watermelon/server/randomevent/repository/LotteryApplierRepository.java
src/main/java/com/watermelon/server/randomevent/service/LotteryService.java
src/main/java/com/watermelon/server/randomevent/service/LotteryServiceImpl.java
src/test/java/com/watermelon/server/Constants.java
src/test/java/com/watermelon/server/DocumentConstants.java
src/test/java/com/watermelon/server/MockLoginInterceptorConfig.java
src/test/java/com/watermelon/server/admin/controller/AdminLotteryControllerTest.java
src/test/java/com/watermelon/server/annotations/ControllerTest.java
src/test/java/com/watermelon/server/randomevent/auth/interceptor/LoginCheckInterceptorTest.java
src/test/java/com/watermelon/server/randomevent/controller/LotteryControllerTest.java
src/test/java/com/watermelon/server/randomevent/link/controller/LinkControllerTest.java
src/test/java/com/watermelon/server/randomevent/link/service/LinkServiceImplTest.java
src/test/java/com/watermelon/server/randomevent/parts/controller/PartsControllerTest.java
src/test/java/com/watermelon/server/randomevent/repository/LotteryApplierRepositoryTest.java
src/test/java/com/watermelon/server/randomevent/service/LotteryServiceImplTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-145
로그인 인터셉터에 회원가입 및 링크 조회수 갱신 기능을 추가하고 테스트했습니다.

Wb 145 api server

---

.github/workflows/docker-deploy.yml

build[api-server]: Docker Container가 AWS CLOUD WATCH에 로그를 보내도록 수정

---

.github/workflows/docker-deploy.yml
src/main/java/com/watermelon/server/ServerApplication.java
src/main/java/com/watermelon/server/redis/config/EmbeddedRedisConfig.java
src/main/java/com/watermelon/server/redis/config/RedissonConfig.java
src/test/java/com/watermelon/server/annotations/ControllerTest.java
src/test/resources/application.yml

WB-155
REDIS CONFIGURATION 수정
@Profile('local')

Wb 155 api server

---

build.gradle
src/main/java/com/watermelon/server/common/config/WebConfig.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-152
노션에 결과 확인 방법과 보는 법을 정리했습니다.
https://www.notion.so/bside/BE-2c5251e4cf5d4c3cab7ef4793a2a5899

Wb 152 api server

---

src/main/java/com/watermelon/server/event/order/domain/OrderEvent.java
src/main/java/com/watermelon/server/event/order/domain/OrderEventReward.java
src/main/java/com/watermelon/server/event/order/domain/Quiz.java
src/main/java/com/watermelon/server/event/order/dto/request/RequestOrderEventDto.java
src/main/java/com/watermelon/server/event/order/error/WrongPhoneNumberFormatException.java
src/test/java/com/watermelon/server/BaseIntegrationTest.java
src/test/java/com/watermelon/server/event/order/controller/OrderEventControllerTest.java
src/test/java/com/watermelon/server/event/order/total/OrderEventTotalTest.java

선착순 이벤트 API 명세서 초본

---

build.gradle

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2
swagger-ui 에서 API 호출 시 사용될 서버 url 을 변경했습니다.

Wb 176 api server

---

src/main/java/com/watermelon/server/admin/controller/AdminOrderEventController.java
src/main/java/com/watermelon/server/admin/service/AdminOrderEventService.java
src/main/java/com/watermelon/server/event/order/domain/OrderEvent.java
src/main/java/com/watermelon/server/event/order/domain/Quiz.java
src/test/java/com/watermelon/server/admin/controller/AdminOrderEventControllerTest.java

WB-178
선착순 이벤트 등록시 퀴즈 이미지도 받도록 수정
@RequestBody 받지 않음

선착순 이벤트 등록 API 수정

---

src/main/java/com/watermelon/server/admin/service/S3ImageService.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-189
- svg, webp 이미지 또한 받을 수 있도록 수정

feat: 선착순 이벤트 생성 이미지 형식 형식

---

src/main/java/com/watermelon/server/admin/controller/AdminOrderEventController.java
src/main/java/com/watermelon/server/admin/service/AdminOrderEventService.java
src/main/java/com/watermelon/server/event/order/service/CurrentOrderEventManageService.java
src/test/java/com/watermelon/server/event/admin/controller/AdminOrderEventControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-210

선착순 어드민 이벤트 삭제 API 구현

---

lottery/src/main/java/com/watermelon/server/event/lottery/service/ExpectationService.java
lottery/src/main/java/com/watermelon/server/event/order/dto/request/RequestQuizDto.java
lottery/src/main/java/com/watermelon/server/event/order/service/OrderEventTestEnvironmentService.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-222
- 기대평 10만개, 선착순 이벤트 5개 자동 생성 클래스

선착순 이벤트 환경 구성 클래스 구현

---

gateway/build.gradle
gateway/src/main/java/com/watermelon/GatewayApplication.java
gateway/src/main/resources/application.yml
settings.gradle

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-220
스프링 클라우드 리액티브 게이트웨이를 초기 설정했습니다.
노션에 관련 내용을 기재하였습니다.
https://www.notion.so/bside/BE-Spring-Cloud-d3c27d9b5f494580b020ae2976eb1216

스프링 클라우드 리액티브 게이트웨이 초기 구성

---

lottery/src/main/java/com/watermelon/server/auth/interceptor/LoginCheckInterceptor.java
lottery/src/main/java/com/watermelon/server/event/lottery/error/ExpectationAlreadyExistError.java
lottery/src/main/java/com/watermelon/server/event/parts/controller/PartsController.java
lottery/src/test/java/com/watermelon/server/auth/interceptor/LoginCheckInterceptorTest.java
lottery/src/test/java/com/watermelon/server/event/lottery/controller/ExpectationControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-239
링크 공유 시 링크 키를 쿠키에 추가하고 서버에서 꺼내 쓰도록 수정했습니다.

공유 시 링크 키를 쿠키에 추가하도록 수정

---

lottery/src/main/java/com/watermelon/server/event/lottery/controller/LotteryController.java
lottery/src/main/java/com/watermelon/server/event/lottery/exception/LotteryApplierNotFoundException.java
lottery/src/main/java/com/watermelon/server/event/lottery/exception/LotteryRewardNotFoundException.java
lottery/src/main/java/com/watermelon/server/event/lottery/service/LotteryRewardServiceImpl.java
lottery/src/main/java/com/watermelon/server/event/lottery/service/LotteryServiceImpl.java
lottery/src/main/java/com/watermelon/server/event/parts/controller/PartsController.java
lottery/src/main/java/com/watermelon/server/event/parts/exception/PartsDrawLimitExceededException.java
lottery/src/main/java/com/watermelon/server/event/parts/exception/PartsNotExistException.java
lottery/src/main/java/com/watermelon/server/event/parts/service/LotteryApplierPartsServiceImpl.java
lottery/src/test/java/com/watermelon/server/APITest.java
lottery/src/test/java/com/watermelon/server/ControllerTest.java
lottery/src/test/java/com/watermelon/server/event/lottery/controller/LotteryControllerTest.java
lottery/src/test/java/com/watermelon/server/event/parts/controller/PartsControllerTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-234

API 예외처리 추가

---

lottery/src/main/java/com/watermelon/server/common/filter/CorsFilter.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-248
CORS 설정을 제거했습니다.

CORS 설정 제거

---

lottery/Dockerfile

jar 파일 이름 수정

---

lottery/Dockerfile
order/src/main/java/com/watermelon/server/order/result/service/OrderResultCommandService.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-263
추첨 서버의 도커 파일에 jar 이름이 잘못되어 수정했습니다.

추첨 서버 도커파일 수정

---

lottery/src/main/java/com/watermelon/server/event/parts/service/PartsServiceImpl.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-265
이전 커밋에서 추가한 테스트 관련 설정을 제거했습니다.

PostConstruct deploy에 영향가지 않도록 수정

---

common/src/main/java/com/watermelon/server/auth/interceptor/LoginCheckInterceptorImpl.java
lottery/src/main/java/com/watermelon/server/common/config/WebConfig.java
lottery/src/main/java/com/watermelon/server/common/constants/PathConstants.java
lottery/src/main/java/com/watermelon/server/event/lottery/controller/ExpectationController.java
lottery/src/main/java/com/watermelon/server/event/lottery/dto/response/ResponseExpectationCheckDto.java
lottery/src/main/java/com/watermelon/server/event/lottery/service/ExpectationService.java
lottery/src/test/java/com/watermelon/server/APITest.java
lottery/src/test/java/com/watermelon/server/ControllerTest.java
lottery/src/test/java/com/watermelon/server/event/admin/controller/AdminExpectationControllerTest.java
lottery/src/test/java/com/watermelon/server/event/lottery/controller/ExpectationControllerTest.java
lottery/src/test/java/com/watermelon/server/integration/BaseIntegrationTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-264
응모자가 기대평을 작성했는지 여부를 반환하는 API를 구현했습니다.

응모자 기대평 존재 여부 반환 API 구현

---

order/src/test/java/com/watermelon/server/order/result/service/OrderResultLockTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-272
커넥션 풀 조정 작업

퀴즈 제출 로직 점검

---

order/src/main/java/com/watermelon/server/order/domain/OrderEventWinner.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-278
OrderEventWinner Id 생성방식 Identity로 수정 
https://www.notion.so/bside/40886f401ea2484faf87fc46c0e4f767?v=c3635c47fcbf4e35aec2b64ba00bf593&p=650bf1dabb1148449b522192557abfae&pm=s

폰 번호 제출 메소드 단일 DB 커넥션으로 수정

---

common/src/main/resources/application.yml
order/src/main/java/com/watermelon/server/common/cache/CacheType.java
order/src/main/java/com/watermelon/server/order/domain/OrderEventWinner.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-278
- OrderWinner 아이디 생성 Identity로 변경
- 톰캣 커넥션 설정 변경

폰 번호 제출 로직 단일 DB 커넥션으로 수정 

---

lottery/src/main/java/com/watermelon/server/event/lottery/repository/LotteryApplierRepository.java
lottery/src/main/java/com/watermelon/server/event/lottery/service/LotteryServiceImpl.java
lottery/src/test/java/com/watermelon/server/integration/LinkIntegrationTest.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-283
원자적 연산으로 다시 수정했습니다.

링크 원자적 연산으로 다시 수정

---

README.md

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-289
- 서버, 배포 아키텍처 이미지 추가

github readme추가

---

.github/workflows/api-lottery-ci.yml
.github/workflows/api-lottery-deploy.yml
.github/workflows/api-order-ci.yml
.github/workflows/api-order-deploy.yml
.github/workflows/swagger.yml
common/src/main/java/com/watermelon/server/S3Config.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-290

CI-CD 파이프라인 개선

---

.github/workflows/swagger.yml
common/src/main/java/com/watermelon/server/S3Config.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-291
파이프라인 개선 테스트입니다.

CI-CD 파이프라인 개선 테스트

---

.github/workflows/swagger.yml
common/src/main/java/com/watermelon/server/S3Config.java

https://watermelon-clap.atlassian.net/jira/software/projects/WB/boards/2?selectedIssue=WB-294

Swagger 파이프라인 gradlew 권한 부여

---

.github/workflows/api-gate-deploy.yml
.github/workflows/api-lottery-ci.yml
.github/workflows/api-lottery-deploy.yml
.github/workflows/api-order-ci.yml
.github/workflows/api-order-deploy.yml
order/src/main/java/com/watermelon/server/Scheduler.java
order/src/main/java/com/watermelon/server/common/config/DatasourceConfig.java
order/src/main/java/com/watermelon/server/orderResult/config/OrderResultDataSourceConfig.java
order/src/main/java/com/watermelon/server/orderResult/repository/OrderApplyCountRepository.java
order/src/main/java/com/watermelon/server/orderResult/service/CurrentOrderEventManageService.java
order/src/main/resources/application.yml

Wb 330 api server
